### ISSUE TITLE
Need help with resetting.

### ISSUE THREAD

**Issue by harsee4all** [filipetedim/angular-rating#7]
Sorry but I am new to it.. I want to know how to get functionality where I can add cross or minus symbol (font awesome) in front of star rating, so that if I want to reset the giving ratting to null or 0. how to do that?

**Comment by filipetedim** [comment]
In front you mean, after the addon? Like a button to reset it?
For that all you need to do is add `ng-click="rating.value = 0"` to any element. You can create a new font awesome icon and add it there:

`<i class="fa fa-times" ng-click="rating.value = 0"></i>`

Example here: https://jsfiddle.net/0595783t/95/
Is this what you wanted?

**Comment by harsee4all** [comment]
Oh yes,

I mean the same what you understood and that is the solution I was looking for. Thank you so much. I tried the same and it’s working great.
